connector:
  llm_provider:
    name: llm_provider
    type: api
    base_url: ${oc.env:LLM_BASE_URL}
    timeout: 5
    retry: 3
    auth:
      type: token
      key_name: apikey
      key_value: ${oc.env:LLM_API_KEY}



