application_configuration:
  env: ${oc.env:APP_ENV,debug}
  run: async

  connector:
    api:
      llm: ${connector.llm_provider}
    database:
      mongodb_checkpointer: ${connector.mongodb_checkpointer}
      sqlite_checkpointer: ${connector.sqlite_checkpointer}
    telemetry:
      open_telemetry: ${connector.telemetry}
    mcp:
      toolbox: ${connector.toolbox}

  operation:
    qwen3-8b: ${operation.qwen3-8b}
    ministral-8b-instruct-2410: ${operation.ministral-8b-instruct-2410}
    lfm2-8b-a1b: ${operation.lfm2-8b-a1b}
    qwen3-14b: ${operation.qwen3-14b}
    gpt-oss-20b: ${operation.gpt-oss-20b}
    lfm2-24b-a2b: ${operation.lfm2-24b-a2b}
    mistral-small-3-2-24b-instruct: ${operation.mistral-small-3-2-24b-instruct}
    gemma4-26b-a4b: ${operation.gemma4-26b-a4b}
    qwen3-30b-a3b-instruct-2507: ${operation.qwen3-30b-a3b-instruct-2507}
    qwen3-32b: ${operation.qwen3-32b}
