application_configuration:
  env: ${oc.env:APP_ENV,debug}
  run: async

  connector:
    api:
      llm: ${connector.llm_provider}
    database:
      mongodb_checkpointer: ${connector.mongodb_checkpointer}
      sqlite_checkpointer: ${connector.sqlite_checkpointer}
    telemetry:
      open_telemetry: ${connector.telemetry}
    mcp:
      toolbox: ${connector.toolbox}

  operation:
    granite4-7b: ${operation.granite4-7b}
