operation:
  granite4-7b:
    name: granite4-7b
    connector: ${connector.llm_provider}
    type: api
    endpoint: /chat/completions
    method: POST
    parameters:
      model: ${operation.granite4-7b.name}
      temperature: 0.0
      max_output_tokens: 8000
      max_context_tokens: 8000
      max_iterations: 20
      use_streaming: true
